name: audioplayer_example
description: a audio player plugin example
version: 2.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  path_provider: ^2.0.2
  http: ^0.13.3
  audioplayer:
    path: ../audioplayer
  audioplayer_web:
    path: ../audioplayer_web

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
